# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20161018_0541'),
        ('likes', '0002_auto_20161018_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comment_like', to='comments.Comment')),
            ],
        ),
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
    ]
