# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20161018_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='video/'),
        ),
    ]
