# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20161018_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
