# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20161028_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-created_at',), 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
