# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20161101_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to='video/'),
        ),
    ]
