# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20161106_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='poster',
            field=models.FileField(default='/home/les/Desktop/Desktop/Web/vidosso/collected_static/images/default-poster.jpg', null=True, upload_to='video/posters/'),
        ),
    ]
