# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_auto_20161106_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=40),
        ),
    ]
