# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_auto_20161106_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='video/posters/'),
        ),
    ]
