# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161106_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default/default-avatar.png', upload_to='avatars'),
        ),
    ]
