# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0006_auto_20161106_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='video',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
